<a href="https://colab.research.google.com/github/Deepsphere-AI/DSAI_Python_Programming/blob/main/Unit-5/Predictive%20Analytics/Program%2095%20-%20CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_CONCATENATING_NUMPY_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:

# *********************************************************************************************************************
  
  # File Name 	:   CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_CONCATENATING_NUMPY_V1
  # Purpose 	:   A Program in Python for Concatenating Arrays using Numpy
  # Author	:   Deepsphere.ai
  # Reviewer 	:   Jothi Periasamy
  # Date 	:   10/26/2022
  # Version	:   1.0	
  
# ***********************************************************************************************************************

## Program Description : Program for Concatenating Arrays using Numpy in Python

## Python Development Environment & Runtime - Python, Anaconda

import numpy as vAR_np

vAR_CSLAB_ARRAY1 = vAR_np.array([[1, 2], [3, 4]])

vAR_CSLAB_ARRAY2 = vAR_np.array([[5, 6]])

print(vAR_np.concatenate((vAR_CSLAB_ARRAY1, vAR_CSLAB_ARRAY2), axis=None))

print(vAR_np.concatenate((vAR_CSLAB_ARRAY1, vAR_CSLAB_ARRAY2), axis=0))

print(vAR_np.concatenate((vAR_CSLAB_ARRAY1, vAR_CSLAB_ARRAY2.T), axis=1))


vAR_CSLAB_ARRAY3 = vAR_np.array([1, 2, 3])

vAR_CSLAB_ARRAY4 = vAR_np.array([4, 5, 6])

vAR_CSLAB_ARRAY5 = vAR_np.stack((vAR_CSLAB_ARRAY3, vAR_CSLAB_ARRAY4), axis=1)

print(vAR_CSLAB_ARRAY5)


vAR_CSLAB_ARRAY6 = vAR_np.hstack((vAR_CSLAB_ARRAY3, vAR_CSLAB_ARRAY4))

print(vAR_CSLAB_ARRAY6)


vAR_CSLAB_ARRAY7 = vAR_np.vstack((vAR_CSLAB_ARRAY3, vAR_CSLAB_ARRAY4))

print(vAR_CSLAB_ARRAY7)

# ****************************************************************************************************************************
#   Disclaimer.

# We are providing this code block strictly for learning and researching, this is not a production
# ready code. We have no liability on this particular code under any circumstances; users should use
# this code on their own risk. All software, hardware and othr products that are referenced in these 
# materials belong to the respective vendor who developed or who owns this product.

# ****************************************************************************************************************************
  

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
