<a href="https://colab.research.google.com/github/Deepsphere-AI/DSAI_Python_Programming/blob/main/Unit-5/Predictive%20Analytics/Program%2094%20-%20CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_RESHAPING_NUMPY_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# *********************************************************************************************************************
  
  # File Name 	:   CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_RESHAPING_NUMPY_V1
  # Purpose 	:   A Program in Python for Reshaping Arrays using Numpy
  # Author	:   Deepsphere.ai
  # Reviewer 	:   Jothi Periasamy
  # Date 	:   10/26/2022
  # Version	:   1.0	
  
# ***********************************************************************************************************************

## Program Description : Program for Reshaping Arrays using Numpy in Python

## Python Development Environment & Runtime - Python, Anaconda

import numpy as vAR_np

vAR_CSLAB_arr = vAR_np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(vAR_CSLAB_arr)

vAR_CSLAB_newarr = vAR_CSLAB_arr.reshape(4, 3)

#print(vAR_CSLAB_newarr)

## Reshaping from 1-D to 3-D

vAR_CSLAB_Reshape1Dto3D = vAR_CSLAB_arr.reshape(2, 3, 2)

print(vAR_CSLAB_Reshape1Dto3D)



vAR_CSLAB_arr = vAR_np.array([1, 2, 3, 4, 5, 6, 7, 8])

#vAR_CSLAB_newarr1 = vAR_CSLAB_arr.reshape(3, 3)

#print(vAR_CSLAB_newarr1) ## Results in a error message


# Flattening the Array

vAR_CSLAB_arr = vAR_np.array([[1, 2, 3], [4, 5, 6]])

print(vAR_CSLAB_arr)

vAR_CSLAB_newarr2 = vAR_CSLAB_arr.reshape(-1)

print(vAR_CSLAB_newarr2)

# ****************************************************************************************************************************
#   Disclaimer.

# We are providing this code block strictly for learning and researching, this is not a production
# ready code. We have no liability on this particular code under any circumstances; users should use
# this code on their own risk. All software, hardware and othr products that are referenced in these 
# materials belong to the respective vendor who developed or who owns this product.

# ****************************************************************************************************************************
  

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
