<a href="https://colab.research.google.com/github/Deepsphere-AI/DSAI_Python_Programming/blob/main/Unit-5/Predictive%20Analytics/Program%2096%20-%20CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_ADDING_NEW_DIMENSIONS_NUMPY_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:

# *********************************************************************************************************************
  
  # File Name 	:   CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_ADDING_NEW_DIMENSIONS_NUMPY_V1
  # Purpose 	:   A Program in Python for Adding New Dimensions to Arrays using Numpy
  # Author	:  Deepsphere.ai
  # Reviewer 	:   Jothi Periasamy
  # Date 	:   10/26/2022
  # Version	:   1.0	
  
# ***********************************************************************************************************************

## Program Description : Program for Adding New Dimensions to Arrays using Numpy in Python

## Python Development Environment & Runtime - Python, Anaconda

import numpy as vAR_np

vAR_CSLAB_ARRAY = vAR_np.array([3,8,10])
print(vAR_CSLAB_ARRAY.shape)

vAR_CSLAB_ARRAY1 = vAR_np.expand_dims(vAR_CSLAB_ARRAY, axis = 0)
print(vAR_CSLAB_ARRAY.shape)

vAR_CSLAB_ARRAY2 = vAR_np.append(vAR_CSLAB_ARRAY1, [[5,7,9]], axis=0)
print(vAR_CSLAB_ARRAY2)


vAR_CSLAB_ARRAY = vAR_np.array(["R","Python","Scala"])
print(vAR_CSLAB_ARRAY.shape)
 
vAR_CSLAB_ARRAY1 = vAR_np.expand_dims(vAR_CSLAB_ARRAY, axis = 0)
print(vAR_CSLAB_ARRAY.shape)
 
vAR_CSLAB_ARRAY2 = vAR_np.append(vAR_CSLAB_ARRAY1, [["Java","C","C++"]], axis=0)
print(vAR_CSLAB_ARRAY2)

## Adding a New Dimension using np.newaxis

vAR_CSLAB_ARRAY = vAR_np.array([50,60,70])
print(vAR_CSLAB_ARRAY.shape)
 
vAR_CSLAB_ARRAY1 = vAR_CSLAB_ARRAY[vAR_np.newaxis]
print(vAR_CSLAB_ARRAY1.shape)
 
vAR_CSLAB_ARRAY2 = vAR_np.append(vAR_CSLAB_ARRAY1, [[80,90,100]], axis=0)
print(vAR_CSLAB_ARRAY2)


vAR_CSLAB_ARRAY = vAR_np.array(["R","Python","Scala"])
print(vAR_CSLAB_ARRAY.shape)
 
vAR_CSLAB_ARRAY1 = vAR_CSLAB_ARRAY[vAR_np.newaxis]
print(vAR_CSLAB_ARRAY1.shape)
 
vAR_CSLAB_ARRAY2 = vAR_np.append(vAR_CSLAB_ARRAY1, [["Java","C","C++"]], axis=0)
print(vAR_CSLAB_ARRAY2)

# ****************************************************************************************************************************
#   Disclaimer.

# We are providing this code block strictly for learning and researching, this is not a production
# ready code. We have no liability on this particular code under any circumstances; users should use
# this code on their own risk. All software, hardware and othr products that are referenced in these 
# materials belong to the respective vendor who developed or who owns this product.

# ****************************************************************************************************************************
  

(3,)
(3,)
[[ 3  8 10]
 [ 5  7  9]]
(3,)
(3,)
[['R' 'Python' 'Scala']
 ['Java' 'C' 'C++']]
(3,)
(1, 3)
[[ 50  60  70]
 [ 80  90 100]]
(3,)
(1, 3)
[['R' 'Python' 'Scala']
 ['Java' 'C' 'C++']]
