<a href="https://colab.research.google.com/github/Deepsphere-AI/DSAI_Python_Programming/blob/main/Unit-5/Predictive%20Analytics/Program%2097%20-%20CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_INITIALIZING_WITH_ZEROS_ONES_NUMPY_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:

# *********************************************************************************************************************
  
  # File Name 	:   CSLAB_SCIENTIFIC_ANALYSIS_ARRAYS_INITIALIZING_WITH_ZEROS_ONES_NUMPY_V1
  # Purpose 	:   A Program in Python for Initializing With Zero's & One's to Arrays using Numpy
  # Author	:   Deepsphere.ai
  # Reviewer 	:   Jothi Periasamy
  # Date 	:   10/26/2022
  # Version	:   1.0	
  
# ***********************************************************************************************************************

## Program Description : Program for Initializing With Zero's & One's to Arrays using Numpy in Python

## Python Development Environment & Runtime - Python, Anaconda

import numpy as vAR_np

vAR_CSLAB_ARRAY = vAR_np.ones((2,3))

vAR_CSLAB_ARRAY1 = vAR_np.ones((3,4),dtype=int)

vAR_CSLAB_ARRAY2 = vAR_np.zeros((2,3))

## Addition of Array's with elements zero and one

vAR_CSLAB_ARRAY3 = vAR_CSLAB_ARRAY + vAR_CSLAB_ARRAY2 

print(vAR_CSLAB_ARRAY3)

## Subtraction of Array's with elements zero and one

vAR_CSLAB_ARRAY4 = vAR_CSLAB_ARRAY - vAR_CSLAB_ARRAY2 

print(vAR_CSLAB_ARRAY4)

## Multiplication of Array's with elements zero and one

vAR_CSLAB_ARRAY5 = vAR_CSLAB_ARRAY * vAR_CSLAB_ARRAY2 

print(vAR_CSLAB_ARRAY5)

## Division of Array's with elements zero and one

vAR_CSLAB_ARRAY6 = vAR_CSLAB_ARRAY / vAR_CSLAB_ARRAY2 

print(vAR_CSLAB_ARRAY6)

# ****************************************************************************************************************************
#   Disclaimer.

# We are providing this code block strictly for learning and researching, this is not a production
# ready code. We have no liability on this particular code under any circumstances; users should use
# this code on their own risk. All software, hardware and othr products that are referenced in these 
# materials belong to the respective vendor who developed or who owns this product.

# ****************************************************************************************************************************
  

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[inf inf inf]
 [inf inf inf]]


<ipython-input-10-470815674dfc>:44: RuntimeWarning: divide by zero encountered in true_divide
  vAR_CSLAB_ARRAY6 = vAR_CSLAB_ARRAY / vAR_CSLAB_ARRAY2
